### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by yikkin** [vortex-ape/Movie-Recommender-System#3]
Hey  Vinayak ,

Few days ago I used your code to inspire me about the same  project I had to lead , 
just wanted to tell you that I found a ML algorithm that beat the KMeans , it is the DBSCAN 
the MSE is not 1.23 it fall to 1.18 seems good to me..
So I wanted to share that piece of information with you ;) 

Take Care man

**Comment by vinayak-mehta** [comment]
Thanks for letting me know @yikkin! I'm planning on updating this repo!
